services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app # for hot reloding
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app # for hot reloading
      - /app/node_modules # to prevent host node_modules from mounting
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-dev

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:5000"
    env_file:
      - ./backend/.env

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-prod
