services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - feedforward_db:/data/db

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://db:27017/feedforward-dev
      - CORS_ORIGIN=value
      - ADMIN_EMAIL=value
      - TOKEN_SECRET=value
      - EMAIL_USER=value
      - EMAIL_APP_PASS=value
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value
    depends_on:
      - db

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5713"
    environment:
      - VITE_API_URL="http://localhost:5000/api/v1/"
    depends_on:
      - backend-dev

  backend-prod:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: prod
    ports:
      - "8080:5000"
    environment:
      - MONGODB_URL=mongodb://db:27017/feedforward-prod
      - CORS_ORIGIN=value
      - ADMIN_EMAIL=value
      - TOKEN_SECRET=value
      - EMAIL_USER=value
      - EMAIL_APP_PASS=value
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value
    depends_on:
      - db

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: prod
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL="http://localhost:5000/api/v1/"
    depends_on:
      - backend-prod

volumes:
  feedforward_db:
