services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app # for hot reloding
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=value
      - CORS_ORIGIN=http://localhost:5173/
      - ADMIN_EMAIL=value
      - TOKEN_SECRET=value
      - EMAIL_USER=value
      - EMAIL_APP_PASS=value
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app # for hot reloading
      - /app/node_modules # to prevent host node_modules from mounting
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1/
    depends_on:
      - backend-dev

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:5000"
    environment:
      - MONGODB_URL=value
      - CORS_ORIGIN=value
      - ADMIN_EMAIL=value
      - TOKEN_SECRET=value
      - EMAIL_USER=value
      - EMAIL_APP_PASS=value
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1/
    depends_on:
      - backend-prod
