services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    command: ["node", "src/index.js"]
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASS=${EMAIL_APP_PASS}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - email-worker-prod
    restart: always

  email-worker-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    command: ["node", "src/workers/emailWorker.js"]
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASS=${EMAIL_APP_PASS}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - redis
    restart: always
