name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: [Run CI]
    types:
      - completed

jobs:
  deploy-backend:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if backend directory changed
        id: changes
        run: |
          echo "CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.workflow_run.head_sha }} | grep '^backend/' || true)" >> $GITHUB_ENV

      - name: Exit if no backend changes
        if: env.CHANGED == ''
        run: |
          echo "No changes in /backend. Skipping deployment."
          exit 0

      - name: Deploy on EC2
        if: env.CHANGED != ''
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd feed-forward || exit 1
            git pull origin main
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker rmi $(docker images -q)
            docker system prune -a
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
